### ISSUE TITLE
Infinite loop when using 'add_speed'

### ISSUE THREAD

**Issue by piyush-jaiswal** [UjjwalSaxena/Automold--Road-Augmentation-Library#5]
[https://github.com/UjjwalSaxena/Automold--Road-Augmentation-Library/blob/d74a2819dddac6cc7ae434c3bcbf9e41d21d05d4/Automold.py#L638-L642](https://github.com/UjjwalSaxena/Automold--Road-Augmentation-Library/blob/d74a2819dddac6cc7ae434c3bcbf9e41d21d05d4/Automold.py#L638-L642)

```i+=imshape[1]//25-count``` followed by ```count += 1``` - ```count``` might become greater than ```imshape[1]//25``` in which case ```i``` starts decreasing and this results in an infinite loop.

**Comment by githubfragments** [comment]
I have met this problem too. How do you solve this problem?
